version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db1
    ports:
      - "3307:3306"
    networks:
      - sqlnetwork1  

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: saidb
      MYSQL_USER: sa
      MYSQL_PASSWORD: 1234

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9080:9080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/saidb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
      MAVEN_HOME=D:\apache-maven-3.6.3-bin\apache-maven-3.6.3
      PATH=D:\apache-maven-3.6.3-bin\apache-maven-3.6.3:$PATH
    networks:
      - sqlnetwork1  
networks:
  sqlnetwork1:
