version: '3.8'
services:

  react-front-end:
    image: "reactapp"
    ports:
      - "3001:3001"
    links:
      - springbootapp

  mysql:
    image: mysql:latest
    container_name: mysql_dbnew
    ports:
      - "3307:3306"
    networks:
      - sqlnetworknew
    environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: saidb
       MYSQL_USER: sa
       MYSQL_PASSWORD: 1234  

  springbootapp:
   
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/saidb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "9080:9080"
    depends_on:
      - mysql
    networks:
      - sqlnetworknew


  networks:
    - sqlnetworknew
